working on hue

diff --git a/hue b/hue
--- a/hue
+++ b/hue
@@ -8,6 +8,39 @@ else
   echo "hue.ini file was not found. Create hue.ini file in /etc/hue.ini."
 fi
 
+while getopts ":djt" OPT; do
+
+  case $OPT in
+    d)
+      DEBUG=1
+      echo "debug mode" >&2
+      ;;
+
+    j)
+      JQDEBUG=1
+      echo "debug mode with jq" >&2
+      ;;
+
+    t)
+      TEXTDEBUG=1
+      echo "debug mode with text" >&2
+      ;;
+
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+
+    :)
+      echo "Option -$OPTARG requires an argument." >&2
+      exit 1
+      ;;
+
+  esac
+done
+
+shift $((OPTIND-1))
+
 ##
 #
 ##
@@ -28,10 +61,7 @@ function call {
     DATA="--data $3"
   fi
 
-  OUTPUT="jq '.'"
-  OUTPUT=""
-
-  curl --silent --request $1 $DATA http://$IP/api/$USERNAME/$2 | jq '.'
+  curl --silent --request $1 $DATA http://$IP/api/$USERNAME/$2 | output
 }
 
 ##
@@ -90,8 +120,13 @@ function set_process {
         shift 2
         ;;
 
-      x|xy)
-        VALUES+=("\"xy\":$2")
+      x)
+        X=$2
+        shift 2
+        ;;
+
+      y)
+        Y=$2
         shift 2
         ;;
 
@@ -120,6 +155,12 @@ function set_process {
         ;;
     esac
   done
+
+
+  if [ $X ] && [ $Y ]; then
+    VALUES+=("\"xy\":[$X,$Y]")
+  fi
+
 
   STATE=$(printf ",%s" "${VALUES[@]}")
   STATE=${STATE:1}
@@ -183,6 +224,36 @@ function alert {
       call PUT lights/$LIGHT/state '{"alert":"select"}'
     done
 
+  fi
+}
+
+function output {
+  read OUTPUT
+
+  if [ $DEBUG ]; then
+    echo $OUTPUT
+  fi
+
+  if [ $JQDEBUG ]; then
+    echo $OUTPUT | jq '.'
+  fi
+
+  if [ $TEXTDEBUG ]; then
+
+    # Hue and Saturation
+    HUE=$(echo $OUTPUT | jq '.state.hue')
+    SATURATION=$(echo $OUTPUT | jq '.state.sat')
+
+    # XY
+    X=$(echo $OUTPUT | jq '.state.xy[0]')
+    Y=$(echo $OUTPUT | jq '.state.xy[1]')
+
+    # COLORTEMPERATURE
+    COLORTEMPERATURE=$(echo $OUTPUT | jq '.state.ct')
+
+    BRIGHTNESS=$(echo $OUTPUT | jq '.state.bri')
+
+    echo "$HUE;$SATURATION;$X;$Y;$COLORTEMPERATURE"
   fi
 }
 
